from debian
COPY setup.sh .
COPY run.sh .
COPY config.ini .
RUN ./setup.sh
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["bash", "run.sh"]
