version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d
    depends_on:
      - database
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./:/code
    depends_on:
      - database

###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    build:
      context: ./docker/database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=crawler
      - MYSQL_USER=username
    volumes:
      - database-data:/var/lib/mysql:rw

volumes:
  database-data:

